working_dir :  # Module data will be written to this path. If not given, use path of this file. Default: not given / empty

dut : dut_mio_ccpdv4.yaml  # DUT hardware configuration (.yaml)
dut_configuration : dut_configuration_mio_ccpdv4.yaml  # DUT init configuration (.yaml)

fe_configuration :  # FE configuration file, text (.cfg) or HDF5 (.h5) file. If not given, latest valid configuration (run status FINISHED) will be taken. If a number is given, configuration from run with specified number will be taken.
fe_flavor : fei4b  # FEI4 flavor/type for initial configuration. Valid values: 'fei4a' or 'fei4b'
chip_address :  # Chip Address for initial configuration, if not given, broadcast bit will be set
module_id : ccpdv4_test  # module identifier / name, sub-folder with given name will be created inside working_dir

