# USBpix board
USB:
    bit_file       : "mio_gpac.bit"  # Selecting FPGA firmware
    board_id       : # Selecting USBpix board by ID
    avoid_download : False  # Avoiding download of FPGA firmware if already initialized

# Trigger
TLU:
    TRIGGER_MODE        : 0  # Selecting trigger mode: Use trigger inputs/trigger select (0), TLU no handshake (1), TLU simple handshake (2), TLU data handshake (3)
    TRIGGER_SELECT      : 0  # Selecting trigger input: CCPD Monitor from GPAC (8), RX2 (TDC loop-through) (4), RX0 (2), MonHit/HitOR from GPAC (1), disabled (0)
    TRIGGER_INVERT      : 0  # Inverting trigger invert
    TRIGGER_VETO_SELECT : 255  # Selecting trigger veto: RX1 (2), RX FIFO full (1), disabled (0)

# TDC for high precision charge measurements
TDC:
    EN_TRIGGER_DIST      : 0  # Measuring trigger to TDC delay with 640MHz clock
    EN_NO_WRITE_TRIG_ERR : 0  # Writing TDC word only if valid trigger occurred
    EN_INVERT_TDC        : 0  # Inverting TDC input
    EN_INVERT_TRIGGER    : 0  # Inverting trigger input

# FE-I4 command output
CMD:
    OUTPUT_MODE : 0  # Selecting command output mode: positive edge (0), negative edge (1), Manchester Code according to IEEE 802.3 (2), Manchester Code according to G.E. Thomas (3)

CCPD_GLOBAL_SPI:
    SIZE : 132

CCPD_CONFIG_SPI:
    SIZE : 336
